### ISSUE TITLE
[Substance-extras] NullPointerException when using new shapers

### ISSUE THREAD

**Issue by jakwarrior** [kirill-grouchnikov/radiance#119]
### Version of Radiance (current development is 2.0-SNAPSHOT)
1.0.2

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance-extras

### Version of Java (current minimum is 8)
Java 8

### Version of OS
Windows 7

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I made my own SubstanceSkin and I wanted to try the new shapers from substance-extras (DolphinButtonShaper, RhinoButtonShaper, StegosaurusButtonShaper). But it doesn't work, I have a nullPointerException in BasePolygonShaper:
```
java.lang.NullPointerException: null
	at org.pushingpixels.substance.extras.api.shaperpack.BasePolygonShaper.getPreferredSize(BasePolygonShaper.java:92) ~[radiance-substance-extras-1.0.2.jar:?]
	at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.getPreferredSize(SubstanceButtonUI.java:373) ~[radiance-substance-1.0.2.jar:?]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) ~[?:1.8.0_51]
	at java.awt.FlowLayout.preferredLayoutSize(FlowLayout.java:414) ~[?:1.8.0_51]
	at java.awt.Container.preferredSize(Container.java:1794) ~[?:1.8.0_51]
	at java.awt.Container.getPreferredSize(Container.java:1778) ~[?:1.8.0_51]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664) ~[?:1.8.0_51]
	at java.awt.CardLayout.preferredLayoutSize(CardLayout.java:281) ~[?:1.8.0_51]
	at java.awt.Container.preferredSize(Container.java:1794) ~[?:1.8.0_51]
	at java.awt.Container.getPreferredSize(Container.java:1778) ~[?:1.8.0_51]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664) ~[?:1.8.0_51]
```

**Comment by kirill-grouchnikov** [comment]
`org.pushingpixels.demo.substance.extras.TestButtons` shows how to use the `SubstanceCortex.ComponentScope.setButtonShaper` API to set one of those button shapes on the specific `JButton`. I don't think I ever tried using those shapers at the skin level.

**Comment by jakwarrior** [comment]
Thanks, it's working with `SubstanceCortex.ComponentScope.setButtonShaper`. In the future, it might be useful to be able to use those shapers at the skin level.

**Comment by kirill-grouchnikov** [comment]
This works for me:

```java
public class TestDolphins extends JFrame {
    public TestDolphins() {
        super("Dolphin buttons");

        this.setLayout(new FlowLayout());
        this.add(new JButton("button 1"));
        this.add(new JButton("button 2"));
    }

    private static class DolphinSkin extends BusinessBlackSteelSkin {
        public DolphinSkin() {
            super();

            this.buttonShaper = new DolphinButtonShaper();
        }

        @Override
        public String getDisplayName() {
            return "Dolphins";
        }
    }

    public static void main(String... args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(() -> {
            SubstanceCortex.GlobalScope.setSkin(new DolphinSkin());
            TestDolphins tb = new TestDolphins();
            tb.invalidate();
            System.out.println(tb.getPreferredSize());
            tb.pack();
            tb.setLocationRelativeTo(null);
            tb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            tb.setVisible(true);
        });
    }
}
```

If you have a similarly-sized standalone sample that reproduces the crash, I'll take a look.

**Comment by jakwarrior** [comment]
The problem occurs in the particular case where the button has no border:

```java
public class TestDolphins extends JFrame {
    public TestDolphins() {
        super("Dolphin buttons");

        this.setLayout(new FlowLayout());
        JButton button1 = new JButton("button 1");
        button1.setBorder(null);

        this.add(button1);
        this.add(new JButton("button 2"));
    }

    private static class DolphinSkin extends BusinessBlackSteelSkin {
        public DolphinSkin() {
            super();

            this.buttonShaper = new DolphinButtonShaper();
        }

        @Override
        public String getDisplayName() {
            return "Dolphins";
        }
    }

    public static void main(String... args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(() -> {
            SubstanceCortex.GlobalScope.setSkin(new DolphinSkin());
            TestDolphins tb = new TestDolphins();
            tb.invalidate();
            System.out.println(tb.getPreferredSize());
            tb.pack();
            tb.setLocationRelativeTo(null);
            tb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            tb.setVisible(true);
        });
    }
}
```

The problem occurs at button level too:

```java
public class TestDolphins extends JFrame {
    public TestDolphins() {
        super("Dolphin buttons");

        this.setLayout(new FlowLayout());
        JButton button1 = new JButton("button 1");
        button1.setBorder(null);
        SubstanceCortex.ComponentScope.setButtonShaper(button1, new DolphinButtonShaper());

        this.add(button1);
        this.add(new JButton("button 2"));
    }

    public static void main(String... args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(() -> {
            SubstanceCortex.GlobalScope.setSkin(new TwilightSkin());
            TestDolphins tb = new TestDolphins();
            tb.invalidate();
            System.out.println(tb.getPreferredSize());
            tb.pack();
            tb.setLocationRelativeTo(null);
            tb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            tb.setVisible(true);
        });
    }
}
```
