### ISSUE TITLE
[flamingo] demo app Small Check Ribbon throws NPE

### ISSUE THREAD

**Issue by extremeCrazyCoder** [kirill-grouchnikov/radiance#122]
### Version of Radiance (current development is 2.0-SNAPSHOT)
current development version downloaded after 0645fbed6a1b1111dd7f7ce8e8afc271b5083f3b

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 8)
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
multiple NPE Expetions when the org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.java file is executed.

1. NPE:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon.getClipboardBand(BasicCheckRibbon.java:544)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.configureRibbon(SmallCheckRibbon.java:50)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.lambda$main$1(SmallCheckRibbon.java:120)

this NPE can be fixed by running 
        `super.createCommands();`
as first command inside configureRibbon (~line 50)

2. NPE:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.flamingo.internal.ui.ribbon.JRibbonGallery.populateContent(JRibbonGallery.java:121)
	at org.pushingpixels.flamingo.internal.ui.ribbon.JRibbonGallery.<init>(JRibbonGallery.java:102)
	at org.pushingpixels.flamingo.api.ribbon.JRibbonBand.addRibbonGallery(JRibbonBand.java:173)
	at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon.getQuickStylesBand(BasicCheckRibbon.java:743)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.configureRibbon(SmallCheckRibbon.java:52)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.lambda$main$1(SmallCheckRibbon.java:121)

I don't have got a fix for this yet

It could be that I have done something wrong when setting up my example build, because I had to rewrite the code a little bit. (I have not found a free version of one of the libraries used: http://www.jgoodies.com/downloads/libraries/ )

Thanks in advance

**Comment by kirill-grouchnikov** [comment]
Forgot to check SmallCheckRibbon when the latest ribbon enhancement round was over. Will upload the fix tonight.

Locally, change BasicCheckRibbon's createCommands and createStyleGalleryModel and call both in SmallCheckRibbon.configureRibbon as the first instructions. And then flip the order of configureTaskBar and configureApplicationMenu a bit later in the same method. Now that task bar shows the usage of an app menu link, it requires first configuring the app menu in the test app.

**Comment by kirill-grouchnikov** [comment]
As for JGoodies downloads, you can get them from Maven at https://mvnrepository.com/artifact/com.jgoodies or from http://www.jgoodies.com/downloads/archive/. Unfortunately the last freely available downloads are from 2015.

**Comment by extremeCrazyCoder** [comment]
Thanks for the fix
I have implemented this
[src.zip](https://github.com/kirill-grouchnikov/radiance/files/2756883/src.zip)

now I am getting another NPE:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Can't add app menu link when app menu is not set
	at org.pushingpixels.flamingo.api.ribbon.JRibbon.addTaskbarAppMenuLink(JRibbon.java:292)
	at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon.configureTaskBar(BasicCheckRibbon.java:1738)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.configureRibbon(SmallCheckRibbon.java:106)
	at org.pushingpixels.demo.flamingo.ribbon.SmallCheckRibbon.lambda$main$1(SmallCheckRibbon.java:123)

I will try out the jgoodies version from maven, but the versions inside the archive look the same and are for Java 6 so I don't that they are going to run with Java 10

**Comment by kirill-grouchnikov** [comment]
See the second part - flipping the order of configureTaskBar and configureApplicationMenu a bit later in the same method. configureApplicationMenu should come first, and configureTaskBar second.

Not sure why you're saying that older JGoodies libs wouldn't run under Java 10. I routinely test demo Radiance apps under Java 10 and 11, and pretty much all of them use FormLayout. I haven't seen any issues.

**Comment by extremeCrazyCoder** [comment]
sorry my fault now this is working

Just to have that said, these Versions of jgoodies are needed (previous Versions don't have the required classes)
https://mvnrepository.com/artifact/com.jgoodies/jgoodies-forms/1.9.0
https://mvnrepository.com/artifact/com.jgoodies/jgoodies-common/1.8.1
I could have read this from https://github.com/kirill-grouchnikov/radiance/blob/master/demos/build.gradle

thanks for your help

**Comment by kirill-grouchnikov** [comment]
Still need to commit the relevant fix. Keeping open until I make the fix tonight.
