### ISSUE TITLE
[Flamingo] Update in-ribbon gallery

### ISSUE THREAD

**Issue by hannespernpeintner** [kirill-grouchnikov/radiance#210]
I think the first thing I will say in every issue here is: Thank you for your extensive libraries and all the effort you did for us!

### Version of Radiance (current development is 3.0-SNAPSHOT)
2.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 9)
jdk-11.0.4+11

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I'm trying to have a in-ribbon gallery that changes its contents. The change can be loaded via a refresh command. My use case is that I'm using radiance stuff and especially flamingo to make a game engine editor and I need to display the set of textures currently loaded for the scene. Since textures can be added at runtime, I have to be able to refresh the gallery.

I'm doing this with a refresh command where I update the gallery contentmodel's command group.

```
.setAction {
  contentModel.getCommandGroupByTitle("Available textures").apply {
    val commands = retrieveTextureCommands()
    SwingUtils.invokeLater {
      removeAllCommands()
      commands.forEach {
        addCommand(it)
      }
    }
  }
}
```

> Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonPanelUI$RowFillLayout.layoutContainer(BasicCommandButtonPanelUI.java:407)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonPanelUI.lambda$installListeners$2(BasicCommandButtonPanelUI.java:146)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:313)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I didn't find any info about if dynamic galleries is even supported, but since there is a listener mechanism in CommandGroup and the possibility to add Commands through a method, I assumed it. Am I doing sth wrong here?

Thanks in advance,
Hannes

**Comment by kirill-grouchnikov** [comment]
That's definitely a use case that should work (in the sense that something like a presentation software should be able to update the list of available templates to apply to the current presentation if you load new templates). Will take a look.

**Comment by hannespernpeintner** [comment]
Impressive response speed!

I already have to correct myself, I think I misused invokeLater. The code above seem to not produce any errors anymore, so I guess I messed up the event thread stuff. Now I have a bunch of commands, but the drop down or the scroll bar is not displayed anymore, although I have more than 3 commands in the gallery.

![before-reload](https://user-images.githubusercontent.com/1679437/67986245-e1491580-fc2a-11e9-8c87-e04b86f72153.png)
![after-refresh](https://user-images.githubusercontent.com/1679437/67986243-e1491580-fc2a-11e9-874b-bce62cd00a7e.png)

**Comment by kirill-grouchnikov** [comment]
The scroll / popup controls are not shown. In addition, there's a variety of different exceptions thrown when such a gallery is opened from the taskbar and then another model change is made. 

That's a good scenario. Thanks for reporting.
