### ISSUE TITLE
[Flamingo] NPE when trying to show keytips with ALT under non-decorated mode

### ISSUE THREAD

**Issue by hannespernpeintner** [kirill-grouchnikov/radiance#213]
### Version of Radiance (current development is 3.0-SNAPSHOT)
2.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 9)
jdk-11.0.4+11

### Version of OS
Ubunut 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I have the ribbon bar and some other components in the other BorderLayout areas. When I hit ALT to show the key tips, I get the following NPE:

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.flamingo.internal.utils.KeyTipManager.showRootKeyTipChain(KeyTipManager.java:232)
	at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$1.eventDispatched(JRibbonFrame.java:418)
	at org.pushingpixels.substance.api.SubstanceLookAndFeel.lambda$initialize$0(SubstanceLookAndFeel.java:230)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2194)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2085)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2085)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2042)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4914)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Since I added a lot of commands, galleries and stuff into the bar and other components into the frame already, I cannot for sure say if the problem exists since ever, or only since a certain thing was added. If you can't get any further with the given information, give me a hint and I try to squeeze out a minimum working example for you, but beware, I somehow have to find the time for that :)

**Comment by kirill-grouchnikov** [comment]
Looks like this crashes when there is no taskbar panel configured for the ribbon. Should be an easy fix :)

**Comment by kirill-grouchnikov** [comment]
Or actually no. `SubstanceRibbonFrameTitlePane.getTaskbarPanel()` can't return null, and neither can `JPanel.getComponents`. So the only way for this to crash is for your `JRibbonFrame` to run in non-decorated mode. Can you confirm that?

**Comment by hannespernpeintner** [comment]
I set `setDefaultLookAndFeelDecorated(true)` so I think I got this.

Funny, I can reproduce the issue with https://github.com/hannespernpeintner/flamingo-issue-212-reproduction also. Just open the frame, hit ALT and the exception should show up.

**Comment by kirill-grouchnikov** [comment]
In that sample, you call it "too late" in the initialization cycle. If you move that call to before `SubstanceCortex.GlobalScope.setSkin` in your `main()` method, then you'll see that you're getting the frame decoration from Substance and not from the system.

**Comment by hannespernpeintner** [comment]
So true! Was so busy with other things that I didn't see the wrong decoration at all.

Fixed it. also added a keytip to the action, hitting ALT doesn't show them up. Anything else I forgot?

**Comment by kirill-grouchnikov** [comment]
You'll need to set the whole chain of keytips, starting at the task level. 

```kotlin
        val configTaskTask = RibbonTask("Config", configBand)
        configTaskTask.keyTip = "A"
```

and then

```kotlin
            addRibbonCommand(command.project(CommandButtonPresentationModel.builder()
                .setTextClickAction()
                .setActionKeyTip("B")
                .build()), JRibbonBand.PresentationPriority.TOP)
```
