### ISSUE TITLE
[Substance] SubstanceSkin#getColorSchemes(String) NPE with custom classloader

### ISSUE THREAD

**Issue by VISTALL** [kirill-grouchnikov/radiance#214]
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
2.5.1

### Version of Java (current minimum is 9)
14
### Version of OS
Windows 10
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Hello. I have modular application, where each plugin have own classloader. 

Substance library loaded in own classloader (which depends to **core** classloader)

You load resources inside constructor
```java
	public GeminiSkin() {
		SubstanceSkin.ColorSchemes schemes = SubstanceSkin
				.getColorSchemes("org/pushingpixels/substance/api/skin/gemini.colorschemes");
}
```

Deeper - you get class loader from

> Thread.currentThread().getContextClassLoader()

will return core classloader (or jdk). We can't set it to Substance classloader (due laf initialized in EDT)

and

> UIManager.get("ClassLoader")

which is wrong, due current Laf is not set (because we inside constructor)

And that will **throw NPE - due resource not found**.

Why not use *SubstanceSkin.class.getClassloader*  or *SubstanceSkin.class.getResource()*?

Thanks.

**Comment by VISTALL** [comment]
Stacktrace
```
Caused by: java.lang.NullPointerException
	at org.pushingpixels.substance.internal.utils.SubstanceColorSchemeUtilities.getColorSchemes(SubstanceColorSchemeUtilities.java:407) ~[?:?]
	at org.pushingpixels.substance.api.SubstanceSkin.getColorSchemes(SubstanceSkin.java:1084) ~[?:?]
	at org.pushingpixels.substance.api.skin.GeminiSkin.<init>(GeminiSkin.java:88) ~[?:?]
	at org.pushingpixels.substance.api.skin.SubstanceGeminiLookAndFeel.<init>(SubstanceGeminiLookAndFeel.java:52) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:442) ~[?:?]
	... 34 more
```

**Comment by kirill-grouchnikov** [comment]
That's a good point, but using `SubstanceSkin`'s class loader won't help either for loading skins from other modules in such a setup. Given that the next release is a major version bump, I'm inclined to change this API to accept `InputStream` instead of a string, and let the specific skin to decide how to load that stream.

**Comment by VISTALL** [comment]
> That's a good point, but using SubstanceSkin's class loader won't help either for loading skins from other modules in such a setup.

But in current situation, Gemini skin load own file which must be exists in same jar file (and same classloader)

**Comment by kirill-grouchnikov** [comment]
Correct, but a `String`-based API that can only work for `.colorschemes` files that are part of Substance itself is not a great API for that situation. As part of this refactoring I'm removing the existing APIs that accept `String` and `URL` and replacing them with a single API that accepts an `InputStream`.

**Comment by VISTALL** [comment]
Will be nice if bundled skins use own skin classloader. For others - yeah, need option for search.

And, if user create own skin class, resources stored inside same jar and classloader (there no sence split them)
