### ISSUE TITLE
[Flamingo] ClassCastException when using KeyTips on toggle anchored ribbon commands

### ISSUE THREAD

**Issue by hannespernpeintner** [kirill-grouchnikov/radiance#226]
### Version of Radiance (current development is 3.0-SNAPSHOT)
Radiance 2.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 9)
11

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I'm getting the following Exception when I activate KeyTips with the alt key.

> Exception in thread "OpenGlAWTCanvas" java.lang.ClassCastException: class org.pushingpixels.flamingo.api.common.JCommandToggleButton cannot be cast to class org.pushingpixels.flamingo.api.common.JCommandButton (org.pushingpixels.flamingo.api.common.JCommandToggleButton and org.pushingpixels.flamingo.api.common.JCommandButton are in unnamed module of loader 'app')
	at org.pushingpixels.flamingo.internal.ui.ribbon.BasicRibbonUI.getAnchoredCommandButtons(BasicRibbonUI.java:1349)
	at org.pushingpixels.flamingo.internal.utils.KeyTipManager.showRootKeyTipChain(KeyTipManager.java:304)
	at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$1.eventDispatched(JRibbonFrame.java:418)
	at org.pushingpixels.substance.api.SubstanceLookAndFeel.lambda$initialize$0(SubstanceLookAndFeel.java:230)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2198)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2046)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4914)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by kirill-grouchnikov** [comment]
No reason to use `JCommandButton` there. Will switch the method and its usage to `List<AbstractCommandButton>`
