### ISSUE TITLE
Apparently an infinite drawing loop

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/radiance#28]
### Version of Radiance

Latest version when it was still called Substance

### Sub-project (Trident, Substance, Flamingo, ...)

Substance

### Version of Java

JDK 10.0.1

### Version of OS

Peppermint Linux 64

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

I believe it's an infinite drawing loop in AWT thread. UI not responsive, got thread dump using VisualVM.

```
"AWT-EventQueue-0" #19 prio=6 os_prio=0 tid=0x00007f38d0581800 nid=0x858 runnable  [0x00007f383e7f3000]
   java.lang.Thread.State: RUNNABLE
        at sun.java2d.marlin.DRenderer.lineTo(java.desktop@10.0.1/DRenderer.java:683)
        at sun.java2d.marlin.DHelpers$PolyStack.popAll(java.desktop@10.0.1/DHelpers.java:650)
        at sun.java2d.marlin.DStroker.emitReverse(java.desktop@10.0.1/DStroker.java:615)
        at sun.java2d.marlin.DStroker.finish(java.desktop@10.0.1/DStroker.java:649)
        at sun.java2d.marlin.DStroker.moveTo(java.desktop@10.0.1/DStroker.java:505)
        at sun.java2d.marlin.DStroker.moveTo(java.desktop@10.0.1/DStroker.java:481)
        at sun.java2d.marlin.DDasher.goTo(java.desktop@10.0.1/DDasher.java:270)
        at sun.java2d.marlin.DDasher.lineTo(java.desktop@10.0.1/DDasher.java:372)
        at sun.java2d.marlin.DMarlinRenderingEngine.pathToLoop(java.desktop@10.0.1/DMarlinRenderingEngine.java:673)
        at sun.java2d.marlin.DMarlinRenderingEngine.pathTo(java.desktop@10.0.1/DMarlinRenderingEngine.java:633)
        at sun.java2d.marlin.DMarlinRenderingEngine.strokeTo(java.desktop@10.0.1/DMarlinRenderingEngine.java:451)
        at sun.java2d.marlin.DMarlinRenderingEngine.strokeTo(java.desktop@10.0.1/DMarlinRenderingEngine.java:224)
        at sun.java2d.marlin.DMarlinRenderingEngine.getAATileGenerator(java.desktop@10.0.1/DMarlinRenderingEngine.java:864)
        at sun.java2d.pipe.AAShapePipe.renderPath(java.desktop@10.0.1/AAShapePipe.java:146)
        at sun.java2d.pipe.AAShapePipe.draw(java.desktop@10.0.1/AAShapePipe.java:77)
        at sun.java2d.pipe.PixelToParallelogramConverter.draw(java.desktop@10.0.1/PixelToParallelogramConverter.java:148)
        at sun.java2d.pipe.ValidatePipe.draw(java.desktop@10.0.1/ValidatePipe.java:154)
        at sun.java2d.SunGraphics2D.draw(java.desktop@10.0.1/SunGraphics2D.java:2498)
        at org.pushingpixels.substance.api.SubstanceConstants$FocusKind$4.paintFocus(SubstanceConstants.java:256)
        at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.paintFocus(SubstanceCoreUtilities.java:1443)
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paint(SubstanceButtonUI.java:399)
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.update(SubstanceButtonUI.java:545)
        at javax.swing.JComponent.paintComponent(java.desktop@10.0.1/JComponent.java:797)
        at javax.swing.JComponent.paint(java.desktop@10.0.1/JComponent.java:1074)
        at javax.swing.JComponent.paintChildren(java.desktop@10.0.1/JComponent.java:907)
        - locked <0x00000000e80f1b78> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@10.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintToOffscreen(java.desktop@10.0.1/JComponent.java:5255)
        at javax.swing.BufferStrategyPaintManager.paint(java.desktop@10.0.1/BufferStrategyPaintManager.java:246)
        at javax.swing.RepaintManager.paint(java.desktop@10.0.1/RepaintManager.java:1313)
        at javax.swing.JComponent._paintImmediately(java.desktop@10.0.1/JComponent.java:5203)
        at javax.swing.JComponent.paintImmediately(java.desktop@10.0.1/JComponent.java:5013)
        at javax.swing.RepaintManager$4.run(java.desktop@10.0.1/RepaintManager.java:857)
        at javax.swing.RepaintManager$4.run(java.desktop@10.0.1/RepaintManager.java:840)
        at java.security.AccessController.doPrivileged(java.base@10.0.1/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@10.0.1/RepaintManager.java:840)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@10.0.1/RepaintManager.java:815)
        at javax.swing.RepaintManager.prePaintDirtyRegions(java.desktop@10.0.1/RepaintManager.java:764)
        at javax.swing.RepaintManager.access$1200(java.desktop@10.0.1/RepaintManager.java:69)
        at javax.swing.RepaintManager$ProcessingRunnable.run(java.desktop@10.0.1/RepaintManager.java:1880)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@10.0.1/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@10.0.1/EventQueue.java:770)
        at java.awt.EventQueue.access$600(java.desktop@10.0.1/EventQueue.java:97)
        at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:721)
        at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:715)
        at java.security.AccessController.doPrivileged(java.base@10.0.1/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
        at java.awt.EventQueue.dispatchEvent(java.desktop@10.0.1/EventQueue.java:740)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@10.0.1/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@10.0.1/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@10.0.1/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@10.0.1/EventDispatchThread.java:90)
```

**Comment by kirill-grouchnikov** [comment]
A default frame button will be constantly pulse-animated under Substance. That is expected. Enabling focus loop will be animating the focused element under certain focus kinds as well.

From this bug report it's not clear what is the specific scenario and a specific button in play. Is there a small sample app that shows the particular behaviour on non-default button?

**Comment by kirill-grouchnikov** [comment]
No sample attached. Closing this.
