### ISSUE TITLE
[Flamingo] Crash in opening a command popup menu from taskbar

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#286]
1. Run `BasicCheckRibbon`
2. Right-click the `Format` button in the `Clipboard` task, and add it to the taskbar
3. Activate that pinned button from the taskbar by clicking it

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.flamingo.api.common.JCommandButtonPanel.createBaseCommandPresentation(JCommandButtonPanel.java:172)
	at org.pushingpixels.flamingo.api.common.JCommandButtonPanel.populateContent(JCommandButtonPanel.java:192)
	at org.pushingpixels.flamingo.api.common.JCommandButtonPanel.<init>(JCommandButtonPanel.java:159)
	at org.pushingpixels.flamingo.api.common.projection.Projection.buildComponent(Projection.java:138)
	at org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.populateContent(JCommandPopupMenu.java:96)
	at org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.<init>(JCommandPopupMenu.java:85)
	at org.pushingpixels.flamingo.api.common.projection.Projection.buildComponent(Projection.java:138)
	at org.pushingpixels.flamingo.api.common.projection.AbstractPopupMenuProjection.buildComponent(AbstractPopupMenuProjection.java:49)
	at org.pushingpixels.flamingo.api.common.JCommandButton.lambda$new$1(JCommandButton.java:424)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonUI.processPopupAction(BasicCommandButtonUI.java:697)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonUI.lambda$createPopupActionListener$6(BasicCommandButtonUI.java:670)
	at org.pushingpixels.flamingo.api.common.JCommandButton$DefaultPopupButtonModel.firePopupActionPerformed(JCommandButton.java:299)
	at org.pushingpixels.flamingo.api.common.JCommandButton$DefaultPopupButtonModel.setPressed(JCommandButton.java:327)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonListener.mousePressed(BasicCommandButtonListener.java:109)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
```

**Comment by kirill-grouchnikov** [comment]
`JRibbon.addTaskbarCommand(Command)` [creates a presentation model](https://github.com/kirill-grouchnikov/radiance/blob/master/flamingo/src/main/java/org/pushingpixels/flamingo/api/ribbon/JRibbon.java#L287) for the passed command:

```java
        CommandButtonPresentationModel presentationModel = CommandButtonPresentationModel.builder()
                .setPresentationState(CommandButtonPresentationState.SMALL)
                .setHorizontalGapScaleFactor(0.5)
                .setVerticalGapScaleFactor(0.5)
                .build();
```

This is used as the default presentation template for that command when it's in the taskbar. However, this is missing any information whatsoever that is needed to present the command button panel that is optional in the popup, such as [this configuration](https://github.com/kirill-grouchnikov/radiance/blob/master/demos/flamingo-demo/src/main/java/org/pushingpixels/demo/flamingo/ribbon/BasicCheckRibbon.java#L653) for the `Format` command projection:

```java
              .project(CommandButtonPresentationModel.builder()
                        .setPopupKeyTip("FP")
                        .setPopupMenuPresentationModel(CommandPopupMenuPresentationModel.builder()
                                .setPanelPresentationModel(
                                        CommandPanelPresentationModel.builder()
                                                .setToShowGroupLabels(false)
                                                .setCommandPresentationState(
                                                        CommandButtonPresentationState.FIT_TO_ICON)
                                                .setCommandIconDimension(48)
                                                .setMaxColumns(5)
                                                .setMaxRows(3)
                                                .build())
                                .build())
                        .build());
```

**Comment by kirill-grouchnikov** [comment]
Off the top of my head, there are three possible ways to address that while maintaining the backwards compatibility for this release:

1. The existing `JRibbon.addTaskbarCommand` implementation is augmented with some default popup menu presentation model that defines the panel presentation model.
2. Add a new `JRibbon.configureDefaultTaskbarPopupMenuPresentationModel` API that will accept the default popup menu presentation model and use that in `JRibbon.addTaskbarCommand`.
3. Add a new `JRibbon.addTaskbarCommand(Command, AbstractPopupMenuPresentationModel)` API that will allow the application code to configre the popup menu presentation model on per-command basis.

**Comment by kirill-grouchnikov** [comment]
Options 1 and 2 have been added. Option 3 will be done as part of #287 in 4.0.
