### ISSUE TITLE
[Photon] Cannot access org.pushingpixels.neon.icon.ResizableIcon

### ISSUE THREAD

**Issue by Manudoma** [kirill-grouchnikov/radiance#289]
### Version of Radiance (current development is 3.5-SNAPSHOT)
3.0

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo and photon

### Version of Java (current minimum is 9)
java version "14.0.1" 2020-04-14

### Version of OS
Ubuntu 20.04 LTS

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Following the Intro.md of flamingo.
I created a paste button

`        Command pasteActionCommand = Command.builder()
                .setText("Paste")
                .setExtraText("Paste.textExtra")
                **_.setIconFactory(paste.factory())_**
                .build();

        CommandButtonProjection bigPasteProjection =
                pasteActionCommand.project(
                        CommandButtonPresentationModel.builder()
                                .setPresentationState(CommandButtonPresentationState.BIG)
                                .setFlat(false)
                                .build());

        JComponent bigButton = bigPasteProjection.buildComponent();`

On setIconFactory(paste.factory()) y created my own icon pack with photon and SvgTranscoderTemplateResizable.templ

I get this.

Error:(46, 46) java: incompatible types: org.pushingpixels.neon.icon.ResizableIcon.Factory cannot be converted to org.pushingpixels.neon.api.icon.ResizableIcon.Factory

Full trace:

> Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'org.pushingpixels.flamingo.api.common.model.Command$BaseBuilder org.pushingpixels.flamingo.api.common.model.Command$Builder.setIconFactory(org.pushingpixels.neon.api.icon.ResizableIcon$Factory)'
	at Main.Molde.init(Molde.java:46)
	at Main.Molde.lambda$new$0(Molde.java:35)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Process finished with exit code 0

I attach the two files.
Icon [paste.txt](https://github.com/kirill-grouchnikov/radiance/files/4808625/paste.txt)
Main [Molde.txt](https://github.com/kirill-grouchnikov/radiance/files/4808629/Molde.txt)

**Comment by kirill-grouchnikov** [comment]
In version 3.0 (see [release notes](https://github.com/kirill-grouchnikov/radiance/releases/tag/v3.0.0)) all public Neon APIs have moved into the `org.pushingpixels.neon.api` package. The matching Photon templates have been updated for both [Java](https://github.com/kirill-grouchnikov/radiance/blob/master/photon/src/main/resources/org/pushingpixels/photon/api/transcoder/java/SvgTranscoderTemplateResizable.templ) and [Kotlin](https://github.com/kirill-grouchnikov/radiance/blob/master/photon/src/main/resources/org/pushingpixels/photon/api/transcoder/kotlin/SvgTranscoderTemplateResizable.templ).

Looks like you're using older Photon templates (or icons created with 2.5 or earlier) and newer Flamingo version (3.0 or 3.5-SNAPSHOT).

Flamingo's [intro](https://github.com/kirill-grouchnikov/radiance/blob/v3.0.0/docs/flamingo/Intro.md) doesn't talk about creating icons. When and how did you generate your icon file?

**Comment by kirill-grouchnikov** [comment]
You can see the mismatch in `ResizableIcon` imports (package name) in the two classes that you've attached.

**Comment by kirill-grouchnikov** [comment]
Thanks for verifying!

**Comment by Manudoma** [comment]
> Thanks for verifying!

Thanks you for the help!!!
