### ISSUE TITLE
External Library has a thread internally how to make that invokelater properly.

### ISSUE THREAD

**Issue by DustinMerrell** [kirill-grouchnikov/radiance#344]
### Version of OS Windows 10

I am using a 3rd party library for printing. They have a thread running a printer. I have attempted to wrap this in my own thread and call and invoke later however I still have issues. How would you suggest that I make this invokelater properly to work with substance?

org.pushingpixels.neon.api.UiThreadingViolationException: Component creation must be done on Event Dispatch Thread
	at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.testComponentCreationThreadingViolation(SubstanceCoreUtilities.java:1579)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.createUI(SubstancePanelUI.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:804)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
	at java.desktop/javax.swing.JFrame.createRootPane(JFrame.java:279)
	at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:225)
	at com.wildcrest.j2printerworks.J2TextPrinter.printFlowable(J2TextPrinter.java:192)
	at com.wildcrest.j2printerworks.J2Pageable.flowPaginator(J2Pageable.java:187)
	at com.wildcrest.j2printerworks.J2Pageable.getNumberOfPages(J2Pageable.java:125)
	at com.wildcrest.j2printerworks.J2Printer.mergePageables(J2Printer.java:298)
	at com.wildcrest.j2printerworks.J2Printer.getPageableNoThankYou(J2Printer.java:1542)
	at com.wildcrest.j2printerworks.J2Printer.getPageable(J2Printer.java:1529)
	at com.wildcrest.j2printerworks.J2Printer.privatePrintToPDF(J2Printer.java:1075)
	at com.wildcrest.j2printerworks.J2Printer.access$000(J2Printer.java:48)
	at com.wildcrest.j2printerworks.J2Printer$1.run(J2Printer.java:987)

**Comment by kirill-grouchnikov** [comment]
Looks like http://www.wildcrest.com/Software/J2PrinterWorks/J2PrinterWorksREADME.html and if so, probably it's not being actively developed or maintained any more.

Ordinarily I would say that they would need to fix their code to respect the threading rules of Swing. That may or may not be feasible if they are no longer in business. From my perspective, I have no plans to relax the threading checks in Radiance at the present moment.
