### ISSUE TITLE
[Theming] Delayed exception thrown after updating font of JTree

### ISSUE THREAD

**Issue by gLuEcKsKrAuT** [kirill-grouchnikov/radiance#409]
### Version of Radiance (latest development is 6.5-SNAPSHOT)
6.0.1
6.5-SNAPSHOT
### Sub-project (Common, Animation, Theming, Component, ...)
Theming
### Version of Java (current minimum is 9)
17
### Version of OS
win 10
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Set font at JTree causes NPE at RadianceTreeUI (PropertyChangeListener)

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JTree.treeDidChange()" because "this.tree" is null
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateSize(BasicTreeUI.java:2159)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setLeftChildIndent(BasicTreeUI.java:329)
	at org.pushingpixels.radiance.theming.internal.ui.RadianceTreeUI.lambda$installListeners$0(RadianceTreeUI.java:432)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

[TreeUI_NPE.java.txt](https://github.com/kirill-grouchnikov/radiance/files/9573983/TreeUI_NPE.java.txt)

**Comment by gLuEcKsKrAuT** [comment]
works fine with 6.5-SNAPSHOT
