### ISSUE TITLE
[Theming] Don't try to draw a zero-sized specular highlight in StandardFillPainter

### ISSUE THREAD

**Issue by ed-erwin-tf** [kirill-grouchnikov/radiance#411]
### Windows 10 (accessed via remote desktop)

Getting this stack trace:

java.lang.IllegalArgumentException: Width (0) and height (1) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at org.pushingpixels.radiance.theming.api.painter.fill.StandardFillPainter.getShineImage(StandardFillPainter.java:268)
	at org.pushingpixels.radiance.theming.api.painter.fill.StandardFillPainter.paintContourBackground(StandardFillPainter.java:98)
	at org.pushingpixels.radiance.theming.internal.ui.RadianceSliderUI.paintSliderTrackSelected1X(RadianceSliderUI.java:317)
	at org.pushingpixels.radiance.theming.internal.ui.RadianceSliderUI.lambda$paintTrack$0(RadianceSliderUI.java:239)
	at org.pushingpixels.radiance.common.internal.contrib.flatlaf.HiDPIUtils.paintAtScale1x(HiDPIUtils.java:64)
	at org.pushingpixels.radiance.common.api.RadianceCommonCortex.paintAtScale1x(RadianceCommonCortex.java:317)
	at org.pushingpixels.radiance.theming.internal.ui.RadianceSliderUI.paintTrack(RadianceSliderUI.java:199)
	at org.pushingpixels.radiance.theming.internal.ui.RadianceSliderUI.paint(RadianceSliderUI.java:426)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)

**Comment by kirill-grouchnikov** [comment]
Do you have a zero-sized slider somewhere in your UI?

**Comment by ed-erwin-tf** [comment]
I doubt that I have a 0-sized slider.  It might possibly be squeezed down to 1 pixel in some situation, I suppose.

These lines in StandardFillPainter use integer math and thus could produce 0 instead of 0.5, for example.
            int shineWidth = iw / SCALE;
            int shineHeight = ih / (2 * SCALE);

I think you should just abort drawing the shine if either of those is 0.

If you don't want to do that, is there something I could add to a subclass of JSlider to prevent it being painted when too small?

**Comment by kirill-grouchnikov** [comment]
It's not that the slider is tiny, it's that if it is configured something like this:

```
public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                RadianceThemingCortex.GlobalScope.setSkin(new BusinessSkin());
                JFrame frame = new JFrame();

                JSlider horizontalLTR3 = new JSlider(0, 350, 1);
                horizontalLTR3.setSnapToTicks(true);
                horizontalLTR3.setMajorTickSpacing(20);
                horizontalLTR3.setMinorTickSpacing(5);
                frame.setLayout(new FlowLayout());
                frame.add(horizontalLTR3);

                frame.setSize(400, 200);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                frame.setVisible(true);

            }
        });
```

And runs on a low-DPI screen (no pixel scaling), Radiance will try to draw a one-pixel wide selected part of the slider track, and the math inside `StandardFillPainter` will indeed get to a 0-width offscreen image.
