### ISSUE TITLE
[Component] Crash on displaying rich tooltips on Java 17+

### ISSUE THREAD

**Issue by homebeaver** [kirill-grouchnikov/radiance#413]
Hi Kirill,

when using SVG File Viewer I get this OfBoundsException. To reproduce try to get the tooltip on an icon at right border.

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

![grafik](https://user-images.githubusercontent.com/3493126/194852354-549c83d2-cdf7-4e48-9755-57d7280f9624.png)

Stack trace (line numbers not exact, because I add some log traces):
```

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at java.desktop/java.awt.font.LineBreakMeasurer.nextOffset(LineBreakMeasurer.java:365)
	at java.desktop/java.awt.font.LineBreakMeasurer.nextLayout(LineBreakMeasurer.java:441)
	at java.desktop/java.awt.font.LineBreakMeasurer.nextLayout(LineBreakMeasurer.java:414)
	at org.pushingpixels.radiance.component.internal.ui.common.BasicRichTooltipPanelUI$RichTooltipPanelLayout.layoutContainer(BasicRichTooltipPanelUI.java:345)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.Popup.reset(Popup.java:168)
	at java.desktop/javax.swing.PopupFactory$HeavyWeightPopup.getHeavyWeightPopup(PopupFactory.java:409)
	at java.desktop/javax.swing.PopupFactory.getHeavyWeightPopup(PopupFactory.java:336)
	at java.desktop/javax.swing.PopupFactory.getPopup(PopupFactory.java:291)
	at java.desktop/javax.swing.PopupFactory.getPopup(PopupFactory.java:235)
	at java.desktop/javax.swing.PopupFactory.getPopup(PopupFactory.java:194)
	at org.pushingpixels.radiance.component.api.common.RichTooltipManager.showTipWindow(RichTooltipManager.java:240)
	at org.pushingpixels.radiance.component.api.common.RichTooltipManager$InitialDelayTimerAction.actionPerformed(RichTooltipManager.java:345)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by kirill-grouchnikov** [comment]
Is this only happening for empty title or empty description? I can't reproduce this in the SVG viewer demo.

If this is only happening in those cases, I'd rather throw an exception in the `RichTooltip.Builder.build()` to not accept rich tooltips like that and force application code to provide that content.

**Comment by homebeaver** [comment]
With SVG File Viewer I open the folder
`theming/src/main/java/org/pushingpixels/radiance/theming/internal/svg/`

The titleLabelWidth is calculated in `BasicRichTooltipPanelUI$RichTooltipPanelLayout layoutContainer` line 327. I add a log-trace there:

```
            // The title label
            int titleLabelWidth = parent.getWidth() - ins.left - ins.right;
            if(titleLabelWidth<0)
            	LOG.info("parent Container:"+parent + ", parent.getWidth()="+parent.getWidth() + ", ins.left="+ins.left + ", ins.right="+ins.right);
... results to
INFORMATION: parent Container:org.pushingpixels.radiance.component.internal.ui.common.JRichTooltipPanel[,0,0,1x1,invalid,layout=org.pushingpixels.radiance.component.internal.ui.common.BasicRichTooltipPanelUI$RichTooltipPanelLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.radiance.theming.internal.utils.border.RadianceBorder@372f64a0,flags=9,maximumSize=,minimumSize=,preferredSize=], 
parent.getWidth()=1, ins.left=5, ins.right=5

```
So `titleLabelWidth  `is  -9!

**Comment by kirill-grouchnikov** [comment]
The fix should address the real issue, which is a 1x1 size of the `JRichTooltipPanel`

**Comment by kirill-grouchnikov** [comment]
Comment on the new commit:

This is still addressing the symptom. It should not be getting to a place where the size is 1x1.

The first place to check would be RichTooltipPanelLayout.preferredLayoutSize. The next one would be in RichTooltipManager.showTipWindow or maybe a bit before to track where the size is computed and set on the JRichTooltipPanel. There's a block in lines 205-207 that computes that.

**Comment by homebeaver** [comment]
Hi @kirill-grouchnikov 
I could not find why JRichTooltipPanel is 1x1 

But I can reproduce the problem:
- first I check in 3 simple changes (with main in SvgViewer413 class)

How to reproduce:
- run SvgViewer413 ( I start it from eclipse - I have 3 svg-files in home / flags from bigflag can also be used):

![grafik](https://user-images.githubusercontent.com/3493126/195396056-eda29a24-e237-4166-9886-bdaf382bfda3.png)

- resize the pane
- and move cursor over one svg till tooltip is shown
- the message "**issues/413 ________  parent Container is 1x1**" indicates that the problem occures

![grafik](https://user-images.githubusercontent.com/3493126/195397993-2d7a259e-5915-4408-8847-16437313eea9.png)

**Comment by kirill-grouchnikov** [comment]
Where do I find `SvgViewer413`?

**Comment by homebeaver** [comment]
commit [67b3bf0](https://github.com/homebeaver/radiance/commit/67b3bf026d067d6f9409f2ec4070bc1a01b60e98)

**Comment by kirill-grouchnikov** [comment]
Still not seeing this. Is this happening for you on other machines with different OS / JVM versions?

**Comment by kirill-grouchnikov** [comment]
Ah, I see it now with Java 17

**Comment by kirill-grouchnikov** [comment]
Ugh, I would consider this a regression introduced in the JDK by [this commit](https://github.com/openjdk/jdk/commit/f3ef97263fe7d99696aa3fe1845e6f19eafe3f45), and in particular [this line](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/javax/swing/Popup.java#L165) that sets the popup content to the size of 1x1 before `pack`ing it.

Not much I can do in Radiance to work around this except for short-circuiting and not doing anything in the layout pass if the size is 1x1.
