### ISSUE TITLE
NullPointerException from RadianceRibbonUI

### ISSUE THREAD

**Issue by Zander-Labuschagne** [kirill-grouchnikov/radiance#428]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I'm trying to get a simple ribbon up with one band having one menu command that has two commands but I get this exception. It is very likely that I'm doing something wrong or missing something. I am using the FlatLafLight look and feel but I get the same issue when using the System look and feel.
```
java.lang.NullPointerException
	at org.pushingpixels.radiance.component.internal.theming.ribbon.ui.RadianceRibbonUI.lambda$paintBackground$0(RadianceRibbonUI.java:193)
	at org.pushingpixels.radiance.common.internal.contrib.flatlaf.HiDPIUtils.paintAtScale1x(HiDPIUtils.java:64)
	at org.pushingpixels.radiance.common.api.RadianceCommonCortex.paintAtScale1x(RadianceCommonCortex.java:317)
	at org.pushingpixels.radiance.component.internal.theming.ribbon.ui.RadianceRibbonUI.paintBackground(RadianceRibbonUI.java:188)
	at org.pushingpixels.radiance.component.internal.ui.ribbon.BasicRibbonUI.paint(BasicRibbonUI.java:315)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at org.pushingpixels.radiance.component.internal.ui.ribbon.BasicRibbonUI.update(BasicRibbonUI.java:309)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	```

**Comment by kirill-grouchnikov** [comment]
All Radiance components, including the ribbon, can only be used under the Radiance look and feel. Other configurations are not supported.

**Comment by Zander-Labuschagne** [comment]
Ah that explains it, thanks! I am seeing what I expect to see now.
