### ISSUE TITLE
[Theming] Exception in RadianceTreeUI Change Listener

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#501]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

8.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Theming

### Version of Java (current minimum is 9)

21.0.4+7

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

I am getting an occasional null pointer exception that appears to be coupled with the construction of a JTree and specifically the setting of the  font during the creation.  The JTree instance appears valid, but a call to `tree.updateUI()` is using a null tree value.  Could this be a bug in the library?

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JTree.updateUI()" because "this.tree" is null
	at org.pushingpixels.radiance.theming.internal.ui.RadianceTreeUI.lambda$installListeners$0(RadianceTreeUI.java:438)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kirill-grouchnikov** [comment]
I'll add a defensive check after Chroma work is done
