### ISSUE TITLE
[Flamingo] ApplicationMenu required for changing L&F

### ISSUE THREAD

**Issue by martin-wincierz** [kirill-grouchnikov/radiance#98]
### Version of Radiance (current development is 1.5-SNAPSHOT)
1.0.2

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 8)
10

### Version of OS
Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When changing the look and feel (from one substance l&f to another) the following exception is thrown:

Caused by: java.lang.NullPointerException at org.pushingpixels.flamingo.internal.ui.ribbon.BasicRibbonUI.installComponents(BasicRibbonUI.java:236)
        at org.pushingpixels.flamingo.internal.substance.ribbon.ui.SubstanceRibbonUI.installComponents(SubstanceRibbonUI.java:142)
        at org.pushingpixels.flamingo.internal.ui.ribbon.BasicRibbonUI.installUI(BasicRibbonUI.java:109)
        at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
        at org.pushingpixels.flamingo.api.ribbon.JRibbon.updateUI(JRibbon.java:507)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)

This is because ribbon.getApplicationMenu().getTitle() is called, but the ApplicationMenu is null. Setting the menu removes the problem, but having an ApplicationMenu should not be required.

**Comment by kirill-grouchnikov** [comment]
The fix will be in 1.5-SNAPSHOT since 1.0 is closed for business
